name: Bellefonte MTB Club
favicon: null
layout_spectrum: 0.75449
typography_spectrum: 0.51789
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#618138'
    - '#000500'
    - '#f6faf5'
    - '#adcb75'
    - '#0f589e'
  brandStrength: 0.16203849599696696
  lightness: 0.6917950809001923
  saturation: 0.9771706310566515
  rhythmicContrast: 0.34171187900938094
purpose: []
